export type RiskLevel = "Low" | "Medium" | "High";
export type Milestone = "Discovery" | "Pilot" | "Migration" | "Optimization" | "Expansion" | "Closed Won";

export interface Customer {
  id: string;
  name: string;
  milestone: Milestone;
  risk: RiskLevel;
  blocker?: string;
  consumption: number; // 0-100% of target
  velocity: "Increasing" | "Stable" | "Decreasing";
}

export const CUSTOMERS: Customer[] = [
  { name: "Snorkel AI", id: "0014M00001kwMVDQA2", milestone: "Optimization", risk: "High", consumption: 38, velocity: "Increasing", blocker: "Technical Debt in Legacy System" },
  { name: "Magic Ai, Inc.", id: "0014M00002DLgvxQAD", milestone: "Optimization", risk: "Medium", consumption: 67, velocity: "Stable", blocker: "Budget Approval Pending" },
  { name: "Groq Inc.", id: "0014M00001hPWgzQAG", milestone: "Discovery", risk: "Medium", consumption: 27, velocity: "Increasing", blocker: "Executive Sponsorship Gap" },
  { name: "Uncharted Labs, Inc dba Udio", id: "0014M00002QPgjZQAT", milestone: "Optimization", risk: "High", consumption: 67, velocity: "Decreasing", blocker: "Budget Approval Pending" },
  { name: "Boston Dynamic AI Institute", id: "0014M00002JnrwmQAB", milestone: "Optimization", risk: "Low", consumption: 78, velocity: "Decreasing" },
  { name: "Dreamlands Inc.", id: "001Kf000017fiMqIAI", milestone: "Optimization", risk: "Low", consumption: 16, velocity: "Stable" },
  { name: "Hugging Face", id: "0014M00001hrxUfQAI", milestone: "Pilot", risk: "Medium", consumption: 39, velocity: "Decreasing", blocker: "Executive Sponsorship Gap" },
  { name: "Vocify", id: "0014M00002NlqbCQAR", milestone: "Discovery", risk: "High", consumption: 26, velocity: "Decreasing", blocker: "Security Compliance Review" },
  { name: "Abridge AI Inc.", id: "0014M00001hjf3iQAA", milestone: "Discovery", risk: "Medium", consumption: 50, velocity: "Increasing", blocker: "Executive Sponsorship Gap" },
  { name: "Thread AI", id: "0014M00002OCzzLQAT", milestone: "Optimization", risk: "Medium", consumption: 80, velocity: "Increasing", blocker: "Executive Sponsorship Gap" },
  { name: "Pinecone", id: "0014M00001xBkssQAC", milestone: "Optimization", risk: "Medium", consumption: 79, velocity: "Stable", blocker: "Technical Debt in Legacy System" },
  { name: "Reflection AI, Inc.", id: "0014M00002S335iQAB", milestone: "Pilot", risk: "High", consumption: 74, velocity: "Increasing", blocker: "Lack of Trained Personnel" },
  { name: "Thinking Machines Lab", id: "001Kf000014AJBjIAO", milestone: "Discovery", risk: "Low", consumption: 89, velocity: "Increasing" },
  { name: "Captions.ai", id: "0014M00001ub6bdQAA", milestone: "Expansion", risk: "Low", consumption: 94, velocity: "Increasing" },
  { name: "Helm.ai", id: "0014M00001hN9n6QAC", milestone: "Pilot", risk: "Low", consumption: 27, velocity: "Decreasing" },
  { name: "Ai Runway Inc", id: "0014M00001h3Cz1QAE", milestone: "Pilot", risk: "Medium", consumption: 45, velocity: "Increasing", blocker: "Security Compliance Review" },
  { name: "Climatix, Inc.", id: "001Kf00000wjXQTIA2", milestone: "Migration", risk: "Low", consumption: 56, velocity: "Increasing" },
  { name: "Scale AI, Inc.", id: "0014M00001reaByQAI", milestone: "Migration", risk: "Low", consumption: 72, velocity: "Decreasing" },
  { name: "Boston Dynamics", id: "0014M00001hTCTtQAO", milestone: "Discovery", risk: "Low", consumption: 86, velocity: "Increasing" },
  { name: "Repl.it", id: "0014M00001hVB5eQAG", milestone: "Migration", risk: "Low", consumption: 80, velocity: "Decreasing" },
  { name: "Windsurf", id: "0014M0000201ShhQAE", milestone: "Expansion", risk: "Medium", consumption: 54, velocity: "Increasing", blocker: "Executive Sponsorship Gap" },
  { name: "Chainguard, Inc.", id: "0014M00002JV6MZQA1", milestone: "Optimization", risk: "Low", consumption: 86, velocity: "Decreasing" },
  { name: "Character Technologies Inc.", id: "0014M00002DMZtxQAH", milestone: "Optimization", risk: "High", consumption: 92, velocity: "Stable", blocker: "Security Compliance Review" },
  { name: "[Field Only] FIGURE AI INC.", id: "0014M00002RQxxDQAT", milestone: "Optimization", risk: "Low", consumption: 51, velocity: "Decreasing" },
  { name: "24 7.ai, Inc", id: "0014M00001hr5JuQAI", milestone: "Discovery", risk: "Low", consumption: 97, velocity: "Stable" },
  { name: "BaseTen", id: "0014M00001kBObPQAW", milestone: "Optimization", risk: "Low", consumption: 87, velocity: "Decreasing" },
  { name: "Inflection.AI", id: "0014M00002LHteoQAD", milestone: "Optimization", risk: "Low", consumption: 36, velocity: "Decreasing" },
  { name: "Perplexity AI, Inc.", id: "0014M00002KND8ZQAX", milestone: "Migration", risk: "Low", consumption: 11, velocity: "Increasing" },
  { name: "AssemblyAI", id: "0014M00001hbWrAQAU", milestone: "Optimization", risk: "Low", consumption: 45, velocity: "Increasing" },
  { name: "Atlas AI", id: "0014M00001hUa1YQAS", milestone: "Pilot", risk: "High", consumption: 35, velocity: "Stable", blocker: "Security Compliance Review" },
  { name: "Dyna Robotics Inc.", id: "001Kf000012iqpSIAQ", milestone: "Expansion", risk: "Low", consumption: 26, velocity: "Decreasing" },
  { name: "Arena Intelligence, Inc", id: "001Kf000014BbKvIAK", milestone: "Discovery", risk: "High", consumption: 51, velocity: "Decreasing", blocker: "Lack of Trained Personnel" },
  { name: "Higgsfield Inc.", id: "0014M00002QUKSmQAP", milestone: "Discovery", risk: "Low", consumption: 26, velocity: "Increasing" },
  { name: "Essential AI Labs Inc", id: "0014M00002ODYldQAH", milestone: "Pilot", risk: "Low", consumption: 87, velocity: "Decreasing" },
  { name: "Reve AI, Inc.", id: "0014M00002S4iP1QAJ", milestone: "Pilot", risk: "Low", consumption: 75, velocity: "Stable" },
  { name: "Cognition AI", id: "0014M00002TLcBzQAL", milestone: "Expansion", risk: "Medium", consumption: 85, velocity: "Decreasing", blocker: "Data Sovereignty Concerns" },
  { name: "Physical Intelligence", id: "0014M00002S3pUVQAZ", milestone: "Optimization", risk: "Low", consumption: 76, velocity: "Stable" },
  { name: "Augment Computing Inc.", id: "0014M00002L2Z7sQAF", milestone: "Expansion", risk: "High", consumption: 36, velocity: "Decreasing", blocker: "Executive Sponsorship Gap" },
  { name: "World Labs Technologies, Inc.", id: "0014M00002QRO54QAH", milestone: "Optimization", risk: "Low", consumption: 20, velocity: "Increasing" },
  { name: "Arize", id: "0014M00001ohTavQAE", milestone: "Pilot", risk: "Low", consumption: 94, velocity: "Decreasing" },
  { name: "Fireworks.AI", id: "0014M00002LRi9OQAT", milestone: "Optimization", risk: "Low", consumption: 19, velocity: "Stable" },
  { name: "Hippocratic AI", id: "0014M00002NkmJ5QAJ", milestone: "Pilot", risk: "High", consumption: 52, velocity: "Increasing", blocker: "Budget Approval Pending" },
  { name: "GenBio", id: "0014M00002S2hiFQAR", milestone: "Discovery", risk: "Low", consumption: 23, velocity: "Stable" },
  { name: "Tzafon, Inc.", id: "001Kf0000135PXhIAM", milestone: "Pilot", risk: "Medium", consumption: 15, velocity: "Increasing", blocker: "Lack of Trained Personnel" },
  { name: "LiveX AI", id: "0014M00002NxG7vQAF", milestone: "Discovery", risk: "High", consumption: 79, velocity: "Increasing", blocker: "Lack of Trained Personnel" },
  { name: "General Agents", id: "0014M00002SvcNBQAZ", milestone: "Migration", risk: "Medium", consumption: 42, velocity: "Stable", blocker: "Data Sovereignty Concerns" },
  { name: "H2O.ai", id: "0014M00001hrosTQAQ", milestone: "Pilot", risk: "Low", consumption: 34, velocity: "Decreasing" },
  { name: "Sesame AI, Inc.", id: "0014M00002TFGIFQA5", milestone: "Optimization", risk: "Low", consumption: 86, velocity: "Increasing" },
  { name: "Safe Superintelligence Inc", id: "001Kf00000wk1F1IAI", milestone: "Discovery", risk: "Medium", consumption: 10, velocity: "Stable", blocker: "Security Compliance Review" },
  { name: "LightBeam.ai", id: "0014M00001hcZguQAE", milestone: "Optimization", risk: "Low", consumption: 40, velocity: "Increasing" },
  { name: "MIDJOURNEY, INC", id: "0014M000026qttxQAA", milestone: "Expansion", risk: "High", consumption: 88, velocity: "Decreasing", blocker: "Executive Sponsorship Gap" },
  { name: "Denver Technologies, Inc. dba Warp", id: "0014M00001xh9cXQAQ", milestone: "Pilot", risk: "Medium", consumption: 8, velocity: "Increasing", blocker: "Lack of Trained Personnel" },
  { name: "SandboxAQ", id: "0014M00002GFDH0QAP", milestone: "Expansion", risk: "Low", consumption: 51, velocity: "Stable" },
  { name: "Crusoe Energy Systems Inc.", id: "0014M00001hMM8wQAG", milestone: "Discovery", risk: "High", consumption: 73, velocity: "Increasing", blocker: "Security Compliance Review" },
  { name: "Contextual AI", id: "0014M00002Mt2QrQAJ", milestone: "Expansion", risk: "Low", consumption: 9, velocity: "Decreasing" },
  { name: "Lambda Labs Inc.", id: "0014M00001hgxcIQAQ", milestone: "Migration", risk: "Medium", consumption: 47, velocity: "Decreasing", blocker: "Security Compliance Review" },
  { name: "Anysphere, Inc.", id: "0014M00002RQaCWQA1", milestone: "Discovery", risk: "Medium", consumption: 77, velocity: "Decreasing", blocker: "Executive Sponsorship Gap" },
  { name: "C3.ai", id: "0014M00001h3slkQAA", milestone: "Discovery", risk: "Low", consumption: 55, velocity: "Increasing" },
  { name: "REKA AI PTE. LTD.", id: "0014M00002H2yKJQAZ", milestone: "Discovery", risk: "Medium", consumption: 52, velocity: "Decreasing", blocker: "Technical Debt in Legacy System" },
  { name: "Lambda", id: "0014M00002S19sgQAB", milestone: "Expansion", risk: "High", consumption: 30, velocity: "Decreasing", blocker: "Budget Approval Pending" },
  { name: "Fal - Features & Labels Inc.", id: "0014M00001tJNefQAG", milestone: "Expansion", risk: "Medium", consumption: 64, velocity: "Increasing", blocker: "Lack of Trained Personnel" },
  { name: "Parallel AI / Shapley, Inc", id: "0014M00002S1iHGQAZ", milestone: "Pilot", risk: "Medium", consumption: 46, velocity: "Stable", blocker: "Data Sovereignty Concerns" },
  { name: "Sieve Inc.", id: "0014M00002CbyByQAJ", milestone: "Discovery", risk: "Low", consumption: 28, velocity: "Increasing" },
  { name: "Sambanova Systems, Inc.", id: "0014M00001kkW0rQAE", milestone: "Optimization", risk: "Low", consumption: 58, velocity: "Stable" },
  { name: "Anthropic, Pbc", id: "0014M00001vluJ3QAI", milestone: "Migration", risk: "Medium", consumption: 83, velocity: "Decreasing", blocker: "Executive Sponsorship Gap" },
  { name: "Open AI", id: "0014M00001h3MlVQAU", milestone: "Pilot", risk: "Medium", consumption: 58, velocity: "Decreasing", blocker: "Budget Approval Pending" },
  { name: "CrowdStrike", id: "0014M00001hmMKcQAM", milestone: "Pilot", risk: "Low", consumption: 21, velocity: "Decreasing" },
  { name: "Palo Alto Networks Inc.", id: "0014M00001hRrllQAC", milestone: "Optimization", risk: "Low", consumption: 77, velocity: "Stable" },
  { name: "Chronosphere Inc", id: "0014M00001ioTXjQAM", milestone: "Expansion", risk: "Low", consumption: 21, velocity: "Increasing" },
  { name: "Oracle", id: "0014M00001hRnb1QAC", milestone: "Expansion", risk: "Low", consumption: 82, velocity: "Stable" },
  { name: "Confluent, Inc.", id: "0014M00001hRvteQAC", milestone: "Expansion", risk: "Low", consumption: 38, velocity: "Stable" },
  { name: "International Business Machines Corp.", id: "0014M00001hJxrFQAS", milestone: "Expansion", risk: "Low", consumption: 94, velocity: "Stable" },
  { name: "Kronos Incorporated", id: "0014M00001hmeiwQAA", milestone: "Pilot", risk: "Low", consumption: 32, velocity: "Increasing" },
  { name: "MongoDB, Inc.", id: "0014M00001hNqxwQAC", milestone: "Discovery", risk: "Medium", consumption: 25, velocity: "Stable", blocker: "Budget Approval Pending" },
  { name: "Datadog", id: "0014M00001hJrfFQAS", milestone: "Migration", risk: "Low", consumption: 28, velocity: "Stable" },
  { name: "Adobe,Inc", id: "0014M00001hmhMhQAI", milestone: "Pilot", risk: "Low", consumption: 88, velocity: "Stable" },
  { name: "Moloco, Inc.", id: "0014M00001hoiQeQAI", milestone: "Discovery", risk: "Medium", consumption: 66, velocity: "Increasing", blocker: "Executive Sponsorship Gap" },
  { name: "Salesforce, Inc.", id: "0014M00001hax0DQAQ", milestone: "Migration", risk: "Low", consumption: 20, velocity: "Stable" },
  { name: "Cisco", id: "0014M00001hn5EiQAI", milestone: "Expansion", risk: "Low", consumption: 20, velocity: "Increasing" },
  { name: "Workday, Inc.", id: "0014M00001hmLq3QAE", milestone: "Expansion", risk: "Low", consumption: 91, velocity: "Stable" },
  { name: "Palantir Technologies", id: "0014M00001h5ySDQAY", milestone: "Optimization", risk: "High", consumption: 29, velocity: "Decreasing", blocker: "Security Compliance Review" },
  { name: "Databricks, Inc.", id: "0014M00001h4Cp9QAE", milestone: "Migration", risk: "Medium", consumption: 10, velocity: "Decreasing", blocker: "Technical Debt in Legacy System" },
  { name: "Snowflake Computing, Inc.", id: "0014M00001hZRVQQA4", milestone: "Expansion", risk: "Low", consumption: 51, velocity: "Increasing" },
  { name: "Elasticsearch, Inc.", id: "0014M00001h4KigQAE", milestone: "Migration", risk: "Low", consumption: 40, velocity: "Stable" },
  { name: "Box, Inc.", id: "0014M00001h5wqiQAA", milestone: "Discovery", risk: "Low", consumption: 28, velocity: "Increasing" },
  { name: "Servicenow, Inc.", id: "0014M00001hOjtFQAS", milestone: "Optimization", risk: "Low", consumption: 21, velocity: "Decreasing" },
  { name: "FireHydrant, Inc.", id: "0014M00001hoUz2QAE", milestone: "Optimization", risk: "High", consumption: 11, velocity: "Stable", blocker: "Technical Debt in Legacy System" },
  { name: "Dataminr, Inc.", id: "0014M00001hd73MQAQ", milestone: "Pilot", risk: "Low", consumption: 17, velocity: "Increasing" },
  { name: "Avaya Inc.", id: "0014M00001hSmNUQA0", milestone: "Migration", risk: "Medium", consumption: 67, velocity: "Increasing", blocker: "Security Compliance Review" },
  { name: "DoForms, Inc.", id: "0014M00001hXb0aQAC", milestone: "Discovery", risk: "Medium", consumption: 6, velocity: "Decreasing", blocker: "Executive Sponsorship Gap" },
  { name: "DigitalOcean / Nanobox", id: "0014M00001h4MC1QAM", milestone: "Pilot", risk: "High", consumption: 74, velocity: "Increasing", blocker: "Budget Approval Pending" },
  { name: "TENWEB, INC.", id: "0014M00001hayqCQAQ", milestone: "Expansion", risk: "Medium", consumption: 14, velocity: "Stable", blocker: "Technical Debt in Legacy System" },
  { name: "MicroStrategy", id: "0014M00001hcee5QAA", milestone: "Expansion", risk: "Medium", consumption: 16, velocity: "Decreasing", blocker: "Data Sovereignty Concerns" },
  { name: "Commvault", id: "0014M00001hbnjzQAA", milestone: "Migration", risk: "Low", consumption: 88, velocity: "Increasing" },
  { name: "Cartodb Inc.", id: "0014M00001hQiK7QAK", milestone: "Pilot", risk: "Medium", consumption: 74, velocity: "Stable", blocker: "Technical Debt in Legacy System" },
  { name: "Raintank Inc", id: "0014M00001hr42JQAQ", milestone: "Discovery", risk: "Low", consumption: 74, velocity: "Decreasing" },
  { name: "Rational Retention, LLC", id: "0014M00001hTKwjQAG", milestone: "Optimization", risk: "Medium", consumption: 26, velocity: "Stable", blocker: "Executive Sponsorship Gap" },
  { name: "Knode.ai", id: "0014M00002QRv9PQAT", milestone: "Migration", risk: "High", consumption: 24, velocity: "Increasing", blocker: "Executive Sponsorship Gap" },
  { name: "Catchpoint Systems", id: "0014M00001hTDpQQAW", milestone: "Expansion", risk: "Medium", consumption: 35, velocity: "Stable", blocker: "Executive Sponsorship Gap" },
  { name: "Human Security Inc", id: "0014M00001hdmFYQAY", milestone: "Expansion", risk: "High", consumption: 11, velocity: "Decreasing", blocker: "Executive Sponsorship Gap" },
  { name: "UiPath", id: "0014M00001hqEKlQAM", milestone: "Optimization", risk: "Low", consumption: 38, velocity: "Increasing" },
  { name: "BlueVoyant", id: "0014M00001h5mNMQAY", milestone: "Discovery", risk: "Medium", consumption: 76, velocity: "Stable", blocker: "Technical Debt in Legacy System" },
  { name: "Cockroach Labs", id: "0014M00001hvgWPQAY", milestone: "Pilot", risk: "Medium", consumption: 30, velocity: "Stable", blocker: "Budget Approval Pending" },
  { name: "Alphasense, Inc.", id: "0014M00001h3jz5QAA", milestone: "Expansion", risk: "Medium", consumption: 89, velocity: "Increasing", blocker: "Security Compliance Review" },
  { name: "Appian Corporation", id: "0014M00001hSuueQAC", milestone: "Expansion", risk: "Medium", consumption: 96, velocity: "Increasing", blocker: "Lack of Trained Personnel" },
  { name: "Astronomer Inc.", id: "0014M00001huLftQAE", milestone: "Pilot", risk: "Low", consumption: 33, velocity: "Increasing" },
  { name: "Unqork, Inc.", id: "0014M00001hcagLQAQ", milestone: "Discovery", risk: "Medium", consumption: 80, velocity: "Increasing", blocker: "Budget Approval Pending" },
  { name: "Avepoint Inc.", id: "0014M00001h4MDPQA2", milestone: "Pilot", risk: "High", consumption: 91, velocity: "Increasing", blocker: "Budget Approval Pending" },
  { name: "Unacast Inc", id: "0014M00001hoPXLQA2", milestone: "Expansion", risk: "Medium", consumption: 8, velocity: "Stable", blocker: "Data Sovereignty Concerns" },
  { name: "Enigma Technologies", id: "0014M00001hQ0U5QAK", milestone: "Expansion", risk: "High", consumption: 19, velocity: "Decreasing", blocker: "Data Sovereignty Concerns" },
  { name: "Jorsek Inc.", id: "0014M00001h3sNgQAI", milestone: "Pilot", risk: "Medium", consumption: 69, velocity: "Increasing", blocker: "Lack of Trained Personnel" },
  { name: "Pypestream Inc", id: "0014M00001hhj8lQAA", milestone: "Discovery", risk: "Low", consumption: 23, velocity: "Decreasing" },
  { name: "LogicMonitor PSP Program", id: "0014M00001hmrg6QAA", milestone: "Migration", risk: "Low", consumption: 92, velocity: "Decreasing" },
  { name: "Liveperson, Inc.", id: "0014M00001h4QCKQA2", milestone: "Pilot", risk: "Low", consumption: 83, velocity: "Stable" },
  { name: "Bettercloud, Inc.", id: "0014M00001hrNS5QAM", milestone: "Pilot", risk: "Medium", consumption: 91, velocity: "Stable", blocker: "Executive Sponsorship Gap" },
  { name: "Braze, Inc.", id: "0014M00001hlweaQAA", milestone: "Pilot", risk: "Medium", consumption: 63, velocity: "Increasing", blocker: "Data Sovereignty Concerns" },
  { name: "Sprinklr, Inc.", id: "0014M00001hRqBdQAK", milestone: "Optimization", risk: "Low", consumption: 36, velocity: "Increasing" },
  { name: "Episerver (now Optimizely)", id: "0014M00001mnh6nQAA", milestone: "Pilot", risk: "High", consumption: 26, velocity: "Decreasing", blocker: "Security Compliance Review" },
  { name: "Flashpoint", id: "0014M00001lwYwCQAU", milestone: "Pilot", risk: "Low", consumption: 65, velocity: "Decreasing" },
  { name: "Cohesity, Inc.", id: "0014M00001hsqctQAA", milestone: "Pilot", risk: "Low", consumption: 21, velocity: "Stable" },
  { name: "App Orchid Inc", id: "0014M00001hrxOnQAI", milestone: "Pilot", risk: "Medium", consumption: 53, velocity: "Stable", blocker: "Budget Approval Pending" },
  { name: "Apptivo, Inc.", id: "0014M00001hJreOQAS", milestone: "Migration", risk: "Medium", consumption: 31, velocity: "Decreasing", blocker: "Data Sovereignty Concerns" },
  { name: "Nextiva", id: "0014M00001hd0YKQAY", milestone: "Migration", risk: "High", consumption: 63, velocity: "Stable", blocker: "Executive Sponsorship Gap" },
  { name: "Kiteworks", id: "0014M00001hXdODQA0", milestone: "Expansion", risk: "Low", consumption: 53, velocity: "Increasing" },
  { name: "Flutterflow, Inc.", id: "0014M00001xCyCJQA0", milestone: "Pilot", risk: "Low", consumption: 41, velocity: "Stable" },
  { name: "Rubrik, Inc.", id: "0014M00001hP5Q6QAK", milestone: "Discovery", risk: "High", consumption: 34, velocity: "Stable", blocker: "Data Sovereignty Concerns" },
  { name: "Rescale, Inc.", id: "0014M00001hZdQYQA0", milestone: "Discovery", risk: "Medium", consumption: 91, velocity: "Stable", blocker: "Technical Debt in Legacy System" },
  { name: "Nutanix inc", id: "0014M00001hgKcgQAE", milestone: "Pilot", risk: "Medium", consumption: 81, velocity: "Stable", blocker: "Budget Approval Pending" },
  { name: "Blackline, Inc.", id: "0014M00001hgDMIQA2", milestone: "Migration", risk: "Low", consumption: 85, velocity: "Increasing" },
  { name: "Black Duck Software", id: "0014M00002RRax7QAD", milestone: "Expansion", risk: "Low", consumption: 70, velocity: "Increasing" },
  { name: "Genesys Cloud Services, Inc.", id: "0014M00001n6bFSQAY", milestone: "Pilot", risk: "Medium", consumption: 21, velocity: "Stable", blocker: "Lack of Trained Personnel" },
  { name: "Zoom", id: "0014M00001hcj25QAA", milestone: "Migration", risk: "Low", consumption: 50, velocity: "Decreasing" },
  { name: "Highway9 Networks Inc.", id: "0014M00001xjCY9QAM", milestone: "Pilot", risk: "Low", consumption: 61, velocity: "Stable" },
  { name: "Tick Tock Networks", id: "0014M00001hhETSQA2", milestone: "Pilot", risk: "Low", consumption: 10, velocity: "Increasing" },
  { name: "Twilio Inc.", id: "0014M00001hPJZgQAO", milestone: "Migration", risk: "Low", consumption: 9, velocity: "Stable" },
  { name: "Zendesk", id: "0014M00001hd4e2QAA", milestone: "Expansion", risk: "Low", consumption: 74, velocity: "Decreasing" },
  { name: "Dropbox", id: "0014M00001hNUgDQAW", milestone: "Migration", risk: "Medium", consumption: 70, velocity: "Increasing", blocker: "Lack of Trained Personnel" },
  { name: "Builder", id: "0014M00001hpMq1QAE", milestone: "Discovery", risk: "Medium", consumption: 83, velocity: "Increasing", blocker: "Executive Sponsorship Gap" },
  { name: "Workspot, Inc.", id: "0014M00001hZUmlQAG", milestone: "Pilot", risk: "Low", consumption: 6, velocity: "Increasing" },
  { name: "Ringcentral, Inc.", id: "0014M00001h45wnQAA", milestone: "Pilot", risk: "Low", consumption: 62, velocity: "Stable" },
  { name: "Harness Inc", id: "0014M00001hTEkgQAG", milestone: "Pilot", risk: "High", consumption: 46, velocity: "Stable", blocker: "Technical Debt in Legacy System" },
  { name: "Five9, Inc.", id: "0014M00001hZH76QAG", milestone: "Discovery", risk: "Medium", consumption: 7, velocity: "Increasing", blocker: "Executive Sponsorship Gap" },
  { name: "Ujet Inc", id: "0014M00001lUNtfQAG", milestone: "Optimization", risk: "Low", consumption: 78, velocity: "Decreasing" },
  { name: "Functionize", id: "0014M00001hTscfQAC", milestone: "Optimization", risk: "Low", consumption: 89, velocity: "Decreasing" },
  { name: "Pegasystems Inc.", id: "0014M00001hdknPQAQ", milestone: "Migration", risk: "Medium", consumption: 98, velocity: "Stable", blocker: "Budget Approval Pending" },
  { name: "Kaminario, Inc.", id: "0014M00001hNWbMQAW", milestone: "Expansion", risk: "Low", consumption: 80, velocity: "Increasing" },
  { name: "Expel, Inc.", id: "0014M00001hXf90QAC", milestone: "Discovery", risk: "Low", consumption: 56, velocity: "Decreasing" },
  { name: "Rapid7", id: "0014M00001hKJlNQAW", milestone: "Optimization", risk: "Medium", consumption: 10, velocity: "Increasing", blocker: "Budget Approval Pending" },
  { name: "Sonatype, Inc", id: "0014M00001hP7GYQA0", milestone: "Discovery", risk: "Medium", consumption: 84, velocity: "Decreasing", blocker: "Lack of Trained Personnel" },
  { name: "Akamai Technologies", id: "0014M00001hSoawQAC", milestone: "Expansion", risk: "Medium", consumption: 40, velocity: "Decreasing", blocker: "Technical Debt in Legacy System" },
  { name: "Orbit Media Studios, Inc.", id: "0014M00001hbegzQAA", milestone: "Expansion", risk: "Medium", consumption: 50, velocity: "Increasing", blocker: "Security Compliance Review" },
  { name: "Robin Powered, Inc.", id: "0014M00001he7G4QAI", milestone: "Pilot", risk: "Low", consumption: 15, velocity: "Stable" },
  { name: "OpenRouter LLC", id: "0014M00002RSUCpQAP", milestone: "Migration", risk: "Low", consumption: 6, velocity: "Decreasing" },
  { name: "HYCU, Inc.", id: "0014M00001hJYHqQAO", milestone: "Discovery", risk: "Medium", consumption: 21, velocity: "Increasing", blocker: "Security Compliance Review" },
  { name: "Iron Mountain Incorporated", id: "0014M00001hbhp1QAA", milestone: "Discovery", risk: "Medium", consumption: 74, velocity: "Decreasing", blocker: "Executive Sponsorship Gap" },
  { name: "Nasuni", id: "0014M00001hcRRbQAM", milestone: "Pilot", risk: "High", consumption: 56, velocity: "Decreasing", blocker: "Budget Approval Pending" },
  { name: "Sovos", id: "0014M00001hXnGbQAK", milestone: "Optimization", risk: "Low", consumption: 74, velocity: "Stable" },
  { name: "ID.me", id: "0014M00001hd0ZEQAY", milestone: "Migration", risk: "Low", consumption: 51, velocity: "Decreasing" },
  { name: "Sailpoint Technologies, Inc.", id: "0014M00001hOZOoQAO", milestone: "Discovery", risk: "Medium", consumption: 72, velocity: "Stable", blocker: "Technical Debt in Legacy System" },
  { name: "Starburst Data, Inc.", id: "0014M00001hth4rQAA", milestone: "Optimization", risk: "Low", consumption: 81, velocity: "Decreasing" },
  { name: "Logrocket, Inc.", id: "0014M00001hRerkQAC", milestone: "Optimization", risk: "Medium", consumption: 64, velocity: "Stable", blocker: "Technical Debt in Legacy System" },
  { name: "Netscout Systems, Inc.", id: "0014M00001hrNjoQAE", milestone: "Optimization", risk: "Medium", consumption: 27, velocity: "Increasing", blocker: "Executive Sponsorship Gap" },
  { name: "Precisely Holdings, LLC", id: "0014M00001nlX2uQAE", milestone: "Migration", risk: "Low", consumption: 98, velocity: "Stable" },
  { name: "Healthedge Software, Inc.", id: "0014M00001hdNUYQA2", milestone: "Pilot", risk: "Low", consumption: 49, velocity: "Stable" },
  { name: "Acquia Inc.", id: "0014M00001hY512QAC", milestone: "Expansion", risk: "Low", consumption: 93, velocity: "Decreasing" },
  { name: "DataRobot Inc.", id: "0014M00001hroFhQAI", milestone: "Optimization", risk: "High", consumption: 39, velocity: "Increasing", blocker: "Executive Sponsorship Gap" },
  { name: "Tenable", id: "0014M00001hgGMfQAM", milestone: "Migration", risk: "Low", consumption: 67, velocity: "Stable" },
  { name: "Blue Triangle Technologies, Inc.", id: "0014M00001hO0biQAC", milestone: "Expansion", risk: "High", consumption: 24, velocity: "Stable", blocker: "Budget Approval Pending" },
  { name: "SNYK Inc", id: "0014M00001hOg0FQAS", milestone: "Optimization", risk: "Low", consumption: 36, velocity: "Decreasing" },
  { name: "LOOKOUT INC", id: "0014M00001hZOe7QAG", milestone: "Pilot", risk: "Medium", consumption: 57, velocity: "Stable", blocker: "Security Compliance Review" },
  { name: "Dynatrace", id: "0014M00001hpNSTQA2", milestone: "Expansion", risk: "Low", consumption: 50, velocity: "Increasing" },
  { name: "Datawire, Inc.", id: "0014M00001hWL3xQAG", milestone: "Optimization", risk: "High", consumption: 46, velocity: "Increasing", blocker: "Technical Debt in Legacy System" },
  { name: "Enterprisedb Corporation", id: "0014M00001hdFhbQAE", milestone: "Discovery", risk: "Medium", consumption: 33, velocity: "Increasing", blocker: "Lack of Trained Personnel" },
  { name: "JAGGAER", id: "0014M00001huYyZQAU", milestone: "Expansion", risk: "Medium", consumption: 7, velocity: "Increasing", blocker: "Executive Sponsorship Gap" },
  { name: "Progress Software Corporation", id: "0014M00001h6XE9QAM", milestone: "Discovery", risk: "Low", consumption: 95, velocity: "Stable" },
  { name: "Hubspot, Inc.", id: "0014M00001hP7F1QAK", milestone: "Pilot", risk: "Low", consumption: 94, velocity: "Increasing" },
  { name: "Globalization Partners, LLC", id: "0014M00001h6Lx9QAE", milestone: "Pilot", risk: "Medium", consumption: 89, velocity: "Stable", blocker: "Budget Approval Pending" },
  { name: "Tamr Inc.", id: "0014M00001hcC4uQAE", milestone: "Migration", risk: "Medium", consumption: 18, velocity: "Decreasing", blocker: "Budget Approval Pending" },
  { name: "Ab Initio Software LLC", id: "0014M00001h3UzdQAE", milestone: "Expansion", risk: "Medium", consumption: 36, velocity: "Stable", blocker: "Lack of Trained Personnel" },
  { name: "Virtru Corporation", id: "0014M00001h3WzfQAE", milestone: "Pilot", risk: "Medium", consumption: 73, velocity: "Increasing", blocker: "Budget Approval Pending" },
  { name: "GoTo Technologies USA, LLC", id: "0014M00001hZQZXQA4", milestone: "Expansion", risk: "Medium", consumption: 78, velocity: "Decreasing", blocker: "Executive Sponsorship Gap" },
  { name: "Intersystems Corporation", id: "0014M00001hs7nPQAQ", milestone: "Optimization", risk: "Medium", consumption: 8, velocity: "Increasing", blocker: "Technical Debt in Legacy System" },
  { name: "Prodoscore", id: "0014M00001hYoPMQA0", milestone: "Discovery", risk: "High", consumption: 86, velocity: "Increasing", blocker: "Lack of Trained Personnel" },
  { name: "Smartsheet Inc.", id: "0014M00001hr4X5QAI", milestone: "Discovery", risk: "High", consumption: 34, velocity: "Stable", blocker: "Executive Sponsorship Gap" },
  { name: "GitLab", id: "0014M00001hpfOkQAI", milestone: "Expansion", risk: "Medium", consumption: 47, velocity: "Increasing", blocker: "Data Sovereignty Concerns" },
  { name: "Pantheon Systems, Inc.", id: "0014M00001h3RqiQAE", milestone: "Optimization", risk: "Medium", consumption: 7, velocity: "Decreasing", blocker: "Data Sovereignty Concerns" },
  { name: "Pure Storage, Inc.", id: "0014M00001hRZRDQA4", milestone: "Pilot", risk: "Medium", consumption: 61, velocity: "Decreasing", blocker: "Data Sovereignty Concerns" },
  { name: "Labelbox, Inc", id: "0014M00001hS8C1QAK", milestone: "Discovery", risk: "Low", consumption: 62, velocity: "Decreasing" },
  { name: "Okta, Inc.", id: "0014M00001hrH24QAE", milestone: "Discovery", risk: "Medium", consumption: 36, velocity: "Increasing", blocker: "Data Sovereignty Concerns" },
  { name: "IDB, LLC", id: "0014M00001h4kfbQAA", milestone: "Optimization", risk: "Low", consumption: 19, velocity: "Increasing" },
  { name: "WRITER (fka Qordoba)", id: "0014M00001hlg43QAA", milestone: "Optimization", risk: "Low", consumption: 68, velocity: "Stable" },
  { name: "NetApp", id: "0014M00001hav1CQAQ", milestone: "Migration", risk: "High", consumption: 68, velocity: "Increasing", blocker: "Security Compliance Review" },
  { name: "F5, Inc.", id: "0014M00001hrtJ3QAI", milestone: "Optimization", risk: "Low", consumption: 48, velocity: "Increasing" },
  { name: "Smarsh Inc.", id: "0014M00001hbZ8KQAU", milestone: "Discovery", risk: "Low", consumption: 95, velocity: "Decreasing" },
  { name: "Cloudbees, Inc.", id: "0014M00001hriSNQAY", milestone: "Pilot", risk: "Medium", consumption: 54, velocity: "Stable", blocker: "Data Sovereignty Concerns" },
  { name: "Intento, Inc.", id: "0014M00001htTUxQAM", milestone: "Optimization", risk: "Low", consumption: 57, velocity: "Decreasing" },
  { name: "duplocloud", id: "0014M00001hqyW8QAI", milestone: "Expansion", risk: "Low", consumption: 94, velocity: "Increasing" },
  { name: "Ascension Labs Inc", id: "0014M00001hO3L1QAK", milestone: "Expansion", risk: "Medium", consumption: 9, velocity: "Increasing", blocker: "Lack of Trained Personnel" },
  { name: "Automation Anywhere", id: "0014M00001hrcdaQAA", milestone: "Pilot", risk: "Medium", consumption: 32, velocity: "Increasing", blocker: "Lack of Trained Personnel" },
  { name: "Reputation.com, Inc.", id: "0014M00001hg8TuQAI", milestone: "Pilot", risk: "High", consumption: 90, velocity: "Decreasing", blocker: "Security Compliance Review" },
  { name: "Nauto Inc.", id: "0014M00001hP7FBQA0", milestone: "Expansion", risk: "Medium", consumption: 47, velocity: "Stable", blocker: "Budget Approval Pending" },
  { name: "Veritone", id: "0014M00001hftWeQAI", milestone: "Migration", risk: "Medium", consumption: 23, velocity: "Decreasing", blocker: "Lack of Trained Personnel" },
  { name: "Airship Group, Inc.", id: "0014M00001h4Zt4QAE", milestone: "Pilot", risk: "High", consumption: 75, velocity: "Increasing", blocker: "Executive Sponsorship Gap" },
  { name: "Idea2 Ltd.", id: "0014M00001hd2omQAA", milestone: "Expansion", risk: "Medium", consumption: 17, velocity: "Stable", blocker: "Executive Sponsorship Gap" },
  { name: "ILLUMIO", id: "0014M00001ijJ9aQAE", milestone: "Expansion", risk: "Low", consumption: 89, velocity: "Decreasing" },
  { name: "ZOOMINFO HOLDINGS LLC", id: "0014M00001hn4rRQAQ", milestone: "Migration", risk: "Medium", consumption: 34, velocity: "Stable", blocker: "Security Compliance Review" },
  { name: "Tetrate", id: "0014M00001hn7rnQAA", milestone: "Migration", risk: "Medium", consumption: 29, velocity: "Decreasing", blocker: "Budget Approval Pending" },
  { name: "Aisera", id: "0014M00001hU7xIQAS", milestone: "Optimization", risk: "Low", consumption: 32, velocity: "Increasing" },
  { name: "Impact Tech, Inc", id: "0014M00001h5q2OQAQ", milestone: "Optimization", risk: "Medium", consumption: 71, velocity: "Stable", blocker: "Security Compliance Review" },
  { name: "Mixpanel", id: "0014M00001hgxMTQAY", milestone: "Migration", risk: "High", consumption: 15, velocity: "Decreasing", blocker: "Lack of Trained Personnel" },
  { name: "Liferay Cloud", id: "0014M00001hZzDzQAK", milestone: "Discovery", risk: "High", consumption: 75, velocity: "Decreasing", blocker: "Security Compliance Review" },
  { name: "Material Security", id: "0014M00001hsDhLQAU", milestone: "Expansion", risk: "Medium", consumption: 7, velocity: "Decreasing", blocker: "Data Sovereignty Concerns" },
  { name: "Qlik Technologies Inc.", id: "0014M00001lUOJhQAO", milestone: "Optimization", risk: "Medium", consumption: 64, velocity: "Stable", blocker: "Data Sovereignty Concerns" },
  { name: "Perforce Software", id: "0014M00001hYElCQAW", milestone: "Migration", risk: "Low", consumption: 56, velocity: "Increasing" },
  { name: "Magic Leap", id: "0014M00001hJjORQA0", milestone: "Migration", risk: "Low", consumption: 37, velocity: "Decreasing" },
  { name: "Coder Technologies, Inc.", id: "0014M00001hO3TeQAK", milestone: "Discovery", risk: "High", consumption: 20, velocity: "Decreasing", blocker: "Executive Sponsorship Gap" },
  { name: "BMC Helix, Inc.", id: "001Kf00001BDPOFIA5", milestone: "Expansion", risk: "Low", consumption: 39, velocity: "Decreasing" },
  { name: "Syntasa", id: "0014M00001h60RdQAI", milestone: "Expansion", risk: "Medium", consumption: 53, velocity: "Increasing", blocker: "Executive Sponsorship Gap" },
  { name: "TigerGraph Inc.", id: "0014M00001hm581QAA", milestone: "Pilot", risk: "Medium", consumption: 28, velocity: "Decreasing", blocker: "Budget Approval Pending" },
  { name: "JAMF Software", id: "0014M00001hm3eEQAQ", milestone: "Discovery", risk: "Medium", consumption: 64, velocity: "Decreasing", blocker: "Data Sovereignty Concerns" },
  { name: "Planview", id: "0014M00001h4Z4nQAE", milestone: "Discovery", risk: "Medium", consumption: 38, velocity: "Stable", blocker: "Security Compliance Review" },
  { name: "Cyderes Group, LLC", id: "0014M00001hrdDwQAI", milestone: "Expansion", risk: "High", consumption: 10, velocity: "Increasing", blocker: "Executive Sponsorship Gap" },
  { name: "Anaplan", id: "0014M00001hRghtQAC", milestone: "Discovery", risk: "High", consumption: 65, velocity: "Stable", blocker: "Technical Debt in Legacy System" },
  { name: "Idera", id: "0014M00001hJYHwQAO", milestone: "Expansion", risk: "High", consumption: 21, velocity: "Increasing", blocker: "Lack of Trained Personnel" },
  { name: "CyberFortress", id: "0014M00001j2RydQAE", milestone: "Migration", risk: "Low", consumption: 66, velocity: "Increasing" },
  { name: "Cast AI Group", id: "0014M00001hSSOPQA4", milestone: "Optimization", risk: "Low", consumption: 90, velocity: "Increasing" },
  { name: "Hewlett Packard Enterprise Company", id: "0014M00001hmfcJQAQ", milestone: "Pilot", risk: "Low", consumption: 21, velocity: "Stable" },
  { name: "Iteration, Inc.", id: "0014M00001hW3AdQAK", milestone: "Optimization", risk: "Low", consumption: 64, velocity: "Stable" },
  { name: "Kore, Inc.", id: "0014M00001zbkZdQAI", milestone: "Discovery", risk: "Medium", consumption: 67, velocity: "Decreasing", blocker: "Technical Debt in Legacy System" },
  { name: "SAS Institute Inc.", id: "0014M00001hNyyQQAS", milestone: "Discovery", risk: "Medium", consumption: 22, velocity: "Decreasing", blocker: "Security Compliance Review" },
  { name: "Rapidops Inc.", id: "0014M00001hhlemQAA", milestone: "Optimization", risk: "Low", consumption: 86, velocity: "Increasing" },
  { name: "Dell Technologies Inc.", id: "0014M00001hcTwVQAU", milestone: "Discovery", risk: "Low", consumption: 32, velocity: "Stable" },
  { name: "roboflow", id: "0014M00001iqw5GQAQ", milestone: "Discovery", risk: "Low", consumption: 58, velocity: "Increasing" },
  { name: "ClearBlade, Inc.", id: "0014M00001hPX9dQAG", milestone: "Discovery", risk: "Low", consumption: 85, velocity: "Increasing" },
  { name: "Reliaquest, LLC", id: "0014M00001hrAhWQAU", milestone: "Discovery", risk: "Low", consumption: 41, velocity: "Stable" },
  { name: "Alteryx", id: "0014M00001mAjfAQAS", milestone: "Optimization", risk: "Low", consumption: 64, velocity: "Decreasing" },
  { name: "SalesLoft", id: "0014M00001hXugrQAC", milestone: "Pilot", risk: "Low", consumption: 26, velocity: "Stable" },
  { name: "Pendo.io, Inc.", id: "0014M00001hmgjyQAA", milestone: "Pilot", risk: "Low", consumption: 44, velocity: "Stable" },
  { name: "Appspace Inc.", id: "0014M00001h4vJHQAY", milestone: "Pilot", risk: "Medium", consumption: 75, velocity: "Decreasing", blocker: "Budget Approval Pending" },
  { name: "HighRadius", id: "0014M00001hmhsqQAA", milestone: "Pilot", risk: "Medium", consumption: 70, velocity: "Increasing", blocker: "Executive Sponsorship Gap" },
  { name: "Pindrop", id: "0014M00001hZ6ArQAK", milestone: "Optimization", risk: "Medium", consumption: 9, velocity: "Increasing", blocker: "Security Compliance Review" },
  { name: "Omnibond Systems LLC", id: "0014M00001hMw3vQAC", milestone: "Migration", risk: "Medium", consumption: 29, velocity: "Decreasing", blocker: "Budget Approval Pending" },
  { name: "Workiva Inc.", id: "0014M00001hNJ77QAG", milestone: "Migration", risk: "Low", consumption: 9, velocity: "Decreasing" },
  { name: "Kong Inc.", id: "0014M00001hbZ9MQAU", milestone: "Expansion", risk: "Low", consumption: 44, velocity: "Increasing" },
  { name: "Pryon Incorporated", id: "0014M00001hRQjBQAW", milestone: "Pilot", risk: "Low", consumption: 57, velocity: "Decreasing" },
  { name: "Brinqa", id: "0014M00001hZBH5QAO", milestone: "Discovery", risk: "Low", consumption: 66, velocity: "Decreasing" },
  { name: "Jasper.AI", id: "0014M00001hgnUeQAI", milestone: "Pilot", risk: "Low", consumption: 27, velocity: "Increasing" },
  { name: "SardineAI Corp", id: "0014M00001ojD5gQAE", milestone: "Pilot", risk: "Medium", consumption: 77, velocity: "Decreasing", blocker: "Technical Debt in Legacy System" },
  { name: "BMC Software, Inc.", id: "0014M00001h3cSVQAY", milestone: "Optimization", risk: "Low", consumption: 88, velocity: "Increasing" },
  { name: "Crux Informatics, Inc.", id: "0014M00001hNTEFQA4", milestone: "Migration", risk: "Low", consumption: 78, velocity: "Increasing" },
  { name: "Zimperium", id: "0014M00001hSKQ6QAO", milestone: "Expansion", risk: "Low", consumption: 66, velocity: "Decreasing" },
  { name: "8x8", id: "0014M00001hg5prQAA", milestone: "Optimization", risk: "Low", consumption: 36, velocity: "Increasing" },
  { name: "Asana", id: "0014M00001hKjwLQAS", milestone: "Optimization", risk: "Low", consumption: 85, velocity: "Decreasing" },
  { name: "Tigera, Inc", id: "0014M00001hf2VTQAY", milestone: "Pilot", risk: "Low", consumption: 80, velocity: "Increasing" },
  { name: "Lucidworks, Inc.", id: "0014M00001hlxiMQAQ", milestone: "Pilot", risk: "Low", consumption: 30, velocity: "Decreasing" },
  { name: "Lightbend, Inc.", id: "0014M00001hrh5zQAA", milestone: "Optimization", risk: "Medium", consumption: 43, velocity: "Stable", blocker: "Executive Sponsorship Gap" },
  { name: "Quantum Corporation", id: "0014M00001hfJCkQAM", milestone: "Optimization", risk: "Medium", consumption: 37, velocity: "Decreasing", blocker: "Executive Sponsorship Gap" },
  { name: "Dialpad, Inc.", id: "0014M00001hrOc9QAE", milestone: "Optimization", risk: "Low", consumption: 90, velocity: "Stable" },
  { name: "A10 Networks", id: "0014M00001hcMg3QAE", milestone: "Expansion", risk: "Medium", consumption: 36, velocity: "Stable", blocker: "Technical Debt in Legacy System" },
  { name: "Talkdesk, Inc.", id: "0014M00001hmYlVQAU", milestone: "Pilot", risk: "Medium", consumption: 97, velocity: "Decreasing", blocker: "Technical Debt in Legacy System" },
  { name: "Exterro, Inc.", id: "0014M00001hiEEKQA2", milestone: "Pilot", risk: "Low", consumption: 14, velocity: "Stable" },
  { name: "Jumpcloud Inc.", id: "0014M00001hgBCRQA2", milestone: "Optimization", risk: "Medium", consumption: 38, velocity: "Increasing", blocker: "Data Sovereignty Concerns" },
  { name: "DataVisor", id: "0014M00001hb3yrQAA", milestone: "Migration", risk: "Low", consumption: 87, velocity: "Increasing" },
  { name: "Kentik Technologies, Inc", id: "0014M00001hNBGBQA4", milestone: "Discovery", risk: "Medium", consumption: 48, velocity: "Stable", blocker: "Lack of Trained Personnel" },
  { name: "Armis, Inc.", id: "0014M00001hqqlsQAA", milestone: "Migration", risk: "Low", consumption: 8, velocity: "Increasing" },
  { name: "GeoComply USA Inc", id: "0014M00001hPStiQAG", milestone: "Optimization", risk: "Low", consumption: 73, velocity: "Stable" },
  { name: "Csg Systems International, Inc.", id: "0014M00001hrFMlQAM", milestone: "Optimization", risk: "Medium", consumption: 73, velocity: "Decreasing", blocker: "Technical Debt in Legacy System" },
  { name: "WekaIO", id: "0014M00001hOuWkQAK", milestone: "Expansion", risk: "Low", consumption: 93, velocity: "Stable" },
  { name: "Fastly, Inc.", id: "0014M00001h5wFlQAI", milestone: "Optimization", risk: "Medium", consumption: 60, velocity: "Stable", blocker: "Lack of Trained Personnel" },
  { name: "Netenrich, Inc.", id: "0014M00001hVb0CQAS", milestone: "Discovery", risk: "Medium", consumption: 15, velocity: "Decreasing", blocker: "Executive Sponsorship Gap" },
  { name: "SignalWire", id: "0014M00001hP0g2QAC", milestone: "Discovery", risk: "Low", consumption: 82, velocity: "Decreasing" },
  { name: "Producer.ai / Riffusion", id: "0014M00002M7hFjQAJ", milestone: "Optimization", risk: "Medium", consumption: 86, velocity: "Decreasing", blocker: "Security Compliance Review" },
  { name: "Sentry.io (aka Functional Software Inc.)", id: "0014M00001heCW2QAM", milestone: "Expansion", risk: "Low", consumption: 45, velocity: "Decreasing" },
  { name: "Bounti.ai", id: "0014M00001yhaojQAA", milestone: "Migration", risk: "Low", consumption: 95, velocity: "Stable" },
  { name: "Moises Systems, Inc", id: "0014M00001ojV3hQAE", milestone: "Pilot", risk: "Low", consumption: 9, velocity: "Decreasing" },
  { name: "Liminal AI", id: "0014M00002ODFquQAH", milestone: "Migration", risk: "Medium", consumption: 94, velocity: "Increasing", blocker: "Security Compliance Review" },
  { name: "Gridspace, Inc.", id: "0014M00001hph2DQAQ", milestone: "Migration", risk: "Medium", consumption: 12, velocity: "Decreasing", blocker: "Lack of Trained Personnel" },
  { name: "Glean", id: "0014M00001hUKVwQAO", milestone: "Migration", risk: "Low", consumption: 61, velocity: "Increasing" },
  { name: "Netlify", id: "0014M00001hUoujQAC", milestone: "Discovery", risk: "Low", consumption: 19, velocity: "Increasing" },
  { name: "Inworld AI", id: "0014M0000279F18QAE", milestone: "Expansion", risk: "Medium", consumption: 90, velocity: "Increasing", blocker: "Executive Sponsorship Gap" },
  { name: "Ping Identity Corporation", id: "0014M00001hS6XqQAK", milestone: "Discovery", risk: "Low", consumption: 92, velocity: "Stable" },
  { name: "Docusign, Inc.", id: "0014M00001hd9V4QAI", milestone: "Migration", risk: "High", consumption: 15, velocity: "Decreasing", blocker: "Data Sovereignty Concerns" },
  { name: "LangChain", id: "0014M00002Mu2dXQAR", milestone: "Discovery", risk: "Medium", consumption: 39, velocity: "Stable", blocker: "Budget Approval Pending" },
  { name: "Pagerduty, Inc.", id: "0014M00001hrrT6QAI", milestone: "Optimization", risk: "Low", consumption: 36, velocity: "Increasing" },
  { name: "Instabase, Inc.", id: "0014M00001hPXCGQA4", milestone: "Discovery", risk: "Low", consumption: 42, velocity: "Increasing" },
  { name: "Sysdig Inc.", id: "0014M00001hr74rQAA", milestone: "Expansion", risk: "Low", consumption: 91, velocity: "Decreasing" },
  { name: "HyperFi", id: "001Kf000019igEgIAI", milestone: "Optimization", risk: "High", consumption: 80, velocity: "Decreasing", blocker: "Executive Sponsorship Gap" },
  { name: "Dremio Corporation", id: "0014M00001hNPQAQA4", milestone: "Migration", risk: "Low", consumption: 65, velocity: "Stable" },
  { name: "InfluxData, Inc.", id: "0014M00001h3iE4QAI", milestone: "Expansion", risk: "Medium", consumption: 77, velocity: "Stable", blocker: "Security Compliance Review" },
  { name: "Aerospike, Inc.", id: "0014M00001hsxjYQAQ", milestone: "Optimization", risk: "Medium", consumption: 88, velocity: "Decreasing", blocker: "Executive Sponsorship Gap" },
  { name: "Qumulo, Inc.", id: "0014M00001hcTwXQAU", milestone: "Pilot", risk: "High", consumption: 34, velocity: "Decreasing", blocker: "Data Sovereignty Concerns" },
  { name: "Seismic Software Inc", id: "0014M00001hcqGAQAY", milestone: "Optimization", risk: "Low", consumption: 53, velocity: "Increasing" },
  { name: "Mariadb Usa, Inc.", id: "0014M00001hSvoPQAS", milestone: "Discovery", risk: "High", consumption: 37, velocity: "Decreasing", blocker: "Data Sovereignty Concerns" },
  { name: "Incorta", id: "0014M00001hS4lvQAC", milestone: "Expansion", risk: "Low", consumption: 38, velocity: "Stable" },
  { name: "Domo, Inc.", id: "0014M00001hYc67QAC", milestone: "Expansion", risk: "Medium", consumption: 35, velocity: "Stable", blocker: "Lack of Trained Personnel" },
  { name: "Nylas", id: "0014M00001hovGyQAI", milestone: "Expansion", risk: "Medium", consumption: 14, velocity: "Increasing", blocker: "Security Compliance Review" },
  { name: "Typeface", id: "0014M00002LNSHJQA5", milestone: "Expansion", risk: "Medium", consumption: 72, velocity: "Stable", blocker: "Data Sovereignty Concerns" },
  { name: "ConnectAndSell Inc.", id: "0014M00001hcbehQAA", milestone: "Pilot", risk: "Medium", consumption: 43, velocity: "Stable", blocker: "Data Sovereignty Concerns" },
  { name: "SnapLogic", id: "0014M00001hKJjNQAW", milestone: "Optimization", risk: "Low", consumption: 86, velocity: "Stable" },
  { name: "Teradata Corporation", id: "0014M00001hcZY3QAM", milestone: "Pilot", risk: "Low", consumption: 48, velocity: "Decreasing" },
  { name: "Rill Data, Inc", id: "0014M00001mYskKQAS", milestone: "Pilot", risk: "Low", consumption: 69, velocity: "Increasing" },
  { name: "Striim, Inc.", id: "0014M00001hs6iyQAA", milestone: "Discovery", risk: "High", consumption: 43, velocity: "Stable", blocker: "Data Sovereignty Concerns" },
  { name: "Algolia, Inc.", id: "0014M00001hr21kQAA", milestone: "Expansion", risk: "Medium", consumption: 93, velocity: "Increasing", blocker: "Technical Debt in Legacy System" },
  { name: "Cloudera, Inc.", id: "0014M00001hdGa1QAE", milestone: "Discovery", risk: "Medium", consumption: 84, velocity: "Stable", blocker: "Executive Sponsorship Gap" },
  { name: "Sauce Labs", id: "0014M00001hvbkZQAQ", milestone: "Pilot", risk: "Medium", consumption: 55, velocity: "Increasing", blocker: "Executive Sponsorship Gap" },
  { name: "Bobsled Inc.", id: "0014M00002MUn64QAD", milestone: "Optimization", risk: "Medium", consumption: 31, velocity: "Stable", blocker: "Budget Approval Pending" },
  { name: "StackBlitz", id: "0014M00001hUa2OQAS", milestone: "Discovery", risk: "High", consumption: 51, velocity: "Stable", blocker: "Lack of Trained Personnel" },
  { name: "Yugabyte Inc", id: "0014M00001hdNozQAE", milestone: "Pilot", risk: "Low", consumption: 12, velocity: "Stable" },
  { name: "Reltio, Inc.", id: "0014M00001h65DRQAY", milestone: "Expansion", risk: "Low", consumption: 56, velocity: "Decreasing" },
  { name: "Verra Mobility", id: "0014M00001hdKKpQAM", milestone: "Discovery", risk: "Medium", consumption: 97, velocity: "Increasing", blocker: "Security Compliance Review" },
  { name: "Couchbase, Inc.", id: "0014M00001hru7xQAA", milestone: "Optimization", risk: "High", consumption: 80, velocity: "Stable", blocker: "Executive Sponsorship Gap" },
  { name: "Saviynt", id: "0014M00001hNKNnQAO", milestone: "Pilot", risk: "Low", consumption: 10, velocity: "Decreasing" },
  { name: "juicelabs.co", id: "0014M00001p1zxUQAQ", milestone: "Discovery", risk: "Low", consumption: 29, velocity: "Decreasing" },
  { name: "Domino Data Lab, Inc.", id: "0014M00001henrbQAA", milestone: "Discovery", risk: "Medium", consumption: 73, velocity: "Decreasing", blocker: "Data Sovereignty Concerns" },
  { name: "Clickhouse", id: "0014M00002GH3ZcQAL", milestone: "Discovery", risk: "Low", consumption: 81, velocity: "Decreasing" },
  { name: "Hightouch", id: "0014M00001hi7M3QAI", milestone: "Pilot", risk: "Low", consumption: 40, velocity: "Decreasing" },
  { name: "Managed Methods, Inc.", id: "0014M00001hs3yDQAQ", milestone: "Pilot", risk: "Low", consumption: 51, velocity: "Increasing" },
  { name: "Yellowbrick", id: "0014M00001hae2XQAQ", milestone: "Optimization", risk: "Low", consumption: 46, velocity: "Decreasing" },
  { name: "Exabeam, LLC", id: "0014M00001hKTuDQAW", milestone: "Pilot", risk: "Low", consumption: 34, velocity: "Increasing" },
  { name: "Fivetran", id: "0014M00001hsjh1QAA", milestone: "Optimization", risk: "High", consumption: 93, velocity: "Increasing", blocker: "Budget Approval Pending" },
  { name: "SingleStore", id: "0014M00001hrpoTQAQ", milestone: "Discovery", risk: "Low", consumption: 27, velocity: "Decreasing" },
  { name: "Zesty.io", id: "0014M00001hcfTWQAY", milestone: "Pilot", risk: "Low", consumption: 33, velocity: "Increasing" },
  { name: "Cornerstone OnDemand", id: "0014M00001hmfpOQAQ", milestone: "Discovery", risk: "Low", consumption: 86, velocity: "Increasing" },
  { name: "Redpanda Data, Inc", id: "0014M00002RQa6gQAD", milestone: "Pilot", risk: "Medium", consumption: 82, velocity: "Decreasing", blocker: "Lack of Trained Personnel" },
  { name: "ThoughtSpot, Inc.", id: "0014M00001hZ8JFQA0", milestone: "Optimization", risk: "Medium", consumption: 75, velocity: "Decreasing", blocker: "Budget Approval Pending" },
  { name: "Anyscale, Inc.", id: "0014M00001oUfcVQAS", milestone: "Discovery", risk: "High", consumption: 42, velocity: "Decreasing", blocker: "Technical Debt in Legacy System" },
  { name: "Neo4j, Inc.", id: "0014M00001m8PSOQA2", milestone: "Expansion", risk: "Low", consumption: 30, velocity: "Decreasing" },
  { name: "GridGain Systems", id: "0014M00001hZ9G6QAK", milestone: "Discovery", risk: "High", consumption: 66, velocity: "Decreasing", blocker: "Lack of Trained Personnel" },
  { name: "DAXTARITY INC", id: "0014M00001lxn9AQAQ", milestone: "Expansion", risk: "Low", consumption: 32, velocity: "Decreasing" },
  { name: "PacketFabric", id: "0014M00001hhdefQAA", milestone: "Discovery", risk: "Low", consumption: 73, velocity: "Stable" },
  { name: "Aviatrix Systems, Inc.", id: "0014M00001hivxuQAA", milestone: "Discovery", risk: "Low", consumption: 93, velocity: "Decreasing" },
  { name: "McAfee LLC", id: "0014M00001hPKKxQAO", milestone: "Pilot", risk: "Low", consumption: 79, velocity: "Increasing" },
  { name: "Securiti, Inc", id: "0014M00001ijJ9IQAU", milestone: "Expansion", risk: "Low", consumption: 18, velocity: "Stable" },
  { name: "Cobalt Labs, Inc.", id: "0014M00001h3l17QAA", milestone: "Optimization", risk: "Low", consumption: 41, velocity: "Increasing" },
  { name: "Extreme Networks", id: "0014M00001hcGKkQAM", milestone: "Discovery", risk: "Medium", consumption: 30, velocity: "Decreasing", blocker: "Lack of Trained Personnel" },
  { name: "Twingate", id: "0014M00001p0xBJQAY", milestone: "Expansion", risk: "Low", consumption: 51, velocity: "Increasing" },
  { name: "Fortinet", id: "0014M00001hbEbcQAE", milestone: "Pilot", risk: "Low", consumption: 60, velocity: "Stable" },
  { name: "New Relic Inc", id: "0014M00001h3oUjQAI", milestone: "Optimization", risk: "Low", consumption: 65, velocity: "Decreasing" },
  { name: "Versa Networks", id: "0014M00001hcYMIQA2", milestone: "Pilot", risk: "Low", consumption: 22, velocity: "Increasing" },
  { name: "Arista Networks", id: "0014M00001heeYSQAY", milestone: "Migration", risk: "Medium", consumption: 25, velocity: "Decreasing", blocker: "Budget Approval Pending" },
  { name: "Afero, Inc.", id: "0014M00001hgpyCQAQ", milestone: "Optimization", risk: "Medium", consumption: 53, velocity: "Stable", blocker: "Executive Sponsorship Gap" },
  { name: "Forescout Technologies, Inc.", id: "0014M00001mWcpQQAS", milestone: "Migration", risk: "Medium", consumption: 40, velocity: "Increasing", blocker: "Security Compliance Review" },
  { name: "Egnyte", id: "0014M00001hP7HCQA0", milestone: "Optimization", risk: "Medium", consumption: 91, velocity: "Increasing", blocker: "Executive Sponsorship Gap" },
  { name: "Authentic8", id: "0014M00001hZ5EGQA0", milestone: "Discovery", risk: "Low", consumption: 47, velocity: "Decreasing" },
  { name: "Oasis Labs", id: "0014M00001hcu8tQAA", milestone: "Optimization", risk: "High", consumption: 49, velocity: "Increasing", blocker: "Budget Approval Pending" },
  { name: "Cloudflare, Inc.", id: "0014M00001h6QovQAE", milestone: "Pilot", risk: "Low", consumption: 76, velocity: "Stable" },
  { name: "Zscaler", id: "0014M00001h3ooSQAQ", milestone: "Pilot", risk: "Low", consumption: 14, velocity: "Decreasing" },
  { name: "Qualys Inc.", id: "0014M00001h5wFtQAI", milestone: "Discovery", risk: "Medium", consumption: 22, velocity: "Stable", blocker: "Technical Debt in Legacy System" },
  { name: "Doppel", id: "0014M00002C0zVvQAJ", milestone: "Discovery", risk: "Medium", consumption: 83, velocity: "Increasing", blocker: "Data Sovereignty Concerns" },
  { name: "REPLICATE", id: "0014M00002F7sSZQAZ", milestone: "Discovery", risk: "High", consumption: 18, velocity: "Increasing", blocker: "Executive Sponsorship Gap" },
  { name: "Streak.com (fka Rewardly Inc.)", id: "0014M00001hN7JqQAK", milestone: "Migration", risk: "Low", consumption: 5, velocity: "Decreasing" },
  { name: "Netskope, Inc.", id: "0014M00001hT2SGQA0", milestone: "Discovery", risk: "Low", consumption: 10, velocity: "Increasing" },
  { name: "Sourcegraph", id: "0014M00001hJamZQAS", milestone: "Discovery", risk: "Medium", consumption: 63, velocity: "Decreasing", blocker: "Data Sovereignty Concerns" },
  { name: "Gunpowder Tech LLC", id: "0014M00001ojZ5IQAU", milestone: "Migration", risk: "Low", consumption: 19, velocity: "Increasing" },
  { name: "Sift", id: "0014M00001hJwXjQAK", milestone: "Pilot", risk: "Low", consumption: 23, velocity: "Increasing" },
  { name: "Acalvio Technologies", id: "0014M00001heSSmQAM", milestone: "Migration", risk: "Medium", consumption: 86, velocity: "Stable", blocker: "Budget Approval Pending" },
  { name: "Descript Solutions GmbH", id: "0014M00001hPvO4QAK", milestone: "Discovery", risk: "Low", consumption: 60, velocity: "Decreasing" },
  { name: "Camiolog, Inc.", id: "0014M00001hv1QBQAY", milestone: "Optimization", risk: "Medium", consumption: 60, velocity: "Increasing", blocker: "Executive Sponsorship Gap" },
  { name: "Menlo Security Inc.", id: "0014M00001hgVNAQA2", milestone: "Optimization", risk: "High", consumption: 59, velocity: "Decreasing", blocker: "Executive Sponsorship Gap" },
  { name: "SentinelOne, Inc", id: "0014M00001hT7EaQAK", milestone: "Expansion", risk: "Low", consumption: 67, velocity: "Increasing" },
];
